// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function usePrevious(value) {
  var reference = React.useRef(value);
  React.useEffect((function () {
          reference.current = value;
          return (function (param) {
                    
                  });
        }), [value]);
  return reference.current;
}

export {
  usePrevious ,
  
}
/* react Not a pure module */
