// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "@rescript/std/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "@rescript/std/lib/es6/belt_Option.js";

function useIdRef(id) {
  var el = Belt_Option.getWithDefault(Curry._1(document.getElementById, id), null);
  var ref_ = React.useRef(el);
  React.useEffect((function () {
          ref_.current = el;
          
        }), [
        ref_,
        el
      ]);
  return ref_;
}

export {
  useIdRef ,
  
}
/* react Not a pure module */
