// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ReactSpread(Props) {
  return React.cloneElement(Props.children, Props.props);
}

var make = ReactSpread;

export {
  make ,
  
}
/* react Not a pure module */
