// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Swiper8 from "../src/Swiper8.js";
import * as Belt_Array from "@rescript/std/lib/es6/belt_Array.js";
import * as React$1 from "swiper/react";

import "swiper/swiper.min.css"
;

var posts = [
  {
    title: "Hello World",
    excerpt: "This is my first post",
    url: "https://example.com/hello-world"
  },
  {
    title: "Hello World 2",
    excerpt: "This is my second post",
    url: "https://example.com/hello-world-2"
  },
  {
    title: "Hello World 3",
    excerpt: "This is my third post",
    url: "https://example.com/hello-world-3"
  },
  {
    title: "Hello World 4",
    excerpt: "This is my fourth post",
    url: "https://example.com/hello-world-4"
  },
  {
    title: "Hello World 5",
    excerpt: "This is my fifth post",
    url: "https://example.com/hello-world-5"
  }
];

function $$default(param) {
  var swiperRef = React.useRef(null);
  return React.createElement("div", {
              className: "p-4"
            }, React.createElement("button", {
                  "aria-controls": "swiper-example",
                  className: "inline-flex items-center rounded border border-transparent bg-indigo-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2",
                  onClick: (function (param) {
                      swiperRef.current.swiper.slidePrev();
                      
                    })
                }, "Prev"), React.createElement(React$1.Swiper, {
                  id: "swiper-example",
                  children: Belt_Array.map(posts, (function (post) {
                          return React.createElement(React$1.SwiperSlide, {
                                      children: React.createElement("div", {
                                            tabIndex: 0
                                          }, React.createElement("h1", {
                                                className: "text-xl font-bold"
                                              }, post.title), React.createElement("p", {
                                                dangerouslySetInnerHTML: {
                                                  __html: post.excerpt
                                                }
                                              }), React.createElement("a", {
                                                className: "underline",
                                                href: post.url
                                              }, "Read more"))
                                    });
                        })),
                  allowTouchMove: true,
                  autoHeight: true,
                  loop: true,
                  ref: swiperRef,
                  slidesPerView: 3.5,
                  spaceBetween: 20,
                  tag: "section",
                  "aria-label": "Example Content",
                  onInit: Swiper8.fixA11y,
                  onSlideChange: Swiper8.fixA11y,
                  onSlideChangeTransitionEnd: Swiper8.fixA11y
                }), React.createElement("button", {
                  "aria-controls": "swiper-example",
                  className: "inline-flex items-center rounded border border-transparent bg-indigo-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2",
                  onClick: (function (param) {
                      swiperRef.current.swiper.slideNext();
                      
                    })
                }, "Next"));
}

export {
  posts ,
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
