// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Swiper8 from "../src/Swiper8.js";
import * as Belt_Array from "@rescript/std/lib/es6/belt_Array.js";
import * as Belt_Option from "@rescript/std/lib/es6/belt_Option.js";
import * as React$1 from "swiper/react";

import "swiper/swiper.min.css"
;

import "wicg-inert"
;

var posts = [
  {
    title: "Hello World",
    excerpt: "This is my first post",
    url: "https://example.com/hello-world"
  },
  {
    title: "Hello World 2",
    excerpt: "This is my second post",
    url: "https://example.com/hello-world-2"
  },
  {
    title: "Hello World 3",
    excerpt: "This is my third post",
    url: "https://example.com/hello-world-3"
  },
  {
    title: "Hello World 4",
    excerpt: "This is my fourth post",
    url: "https://example.com/hello-world-4"
  },
  {
    title: "Hello World 5",
    excerpt: "This is my fifth post",
    url: "https://example.com/hello-world-5"
  }
];

function $$default(param) {
  var swiperRef = React.useRef(null);
  return React.createElement("div", {
              className: "p-4"
            }, React.createElement("button", {
                  "aria-controls": "swiper-example",
                  className: "inline-flex items-center rounded border border-transparent bg-indigo-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2",
                  onClick: (function (param) {
                      Belt_Option.forEach(Swiper8.getFromDom(swiperRef.current), (function (prim) {
                              prim.slidePrev();
                            }));
                    })
                }, "Prev"), React.createElement(React$1.Swiper, {
                  id: "swiper-example",
                  children: Belt_Array.map(posts, (function (post) {
                          return React.createElement(React$1.SwiperSlide, {
                                      children: (function (props) {
                                          var el = React.createElement("div", {
                                                "aria-hidden": !props.isVisible,
                                                className: "swiper-slide-contents",
                                                tabIndex: 0
                                              }, React.createElement("div", undefined, "Active: " + (
                                                    props.isVisible ? "true" : "false"
                                                  ) + ""), React.createElement("h2", {
                                                    className: "text-xl font-bold"
                                                  }, post.title), React.createElement("p", {
                                                    dangerouslySetInnerHTML: {
                                                      __html: post.excerpt
                                                    }
                                                  }), React.createElement("a", {
                                                    className: "underline",
                                                    href: post.url
                                                  }, "Read more"));
                                          if (props.isVisible) {
                                            return el;
                                          } else {
                                            return React.cloneElement(el, {
                                                        inert: ""
                                                      });
                                          }
                                        })
                                    });
                        })),
                  allowTouchMove: true,
                  autoHeight: true,
                  loop: true,
                  ref: swiperRef,
                  slidesPerView: 3.5,
                  spaceBetween: 20,
                  tag: "section",
                  "aria-label": "Example Content",
                  onSlideNextTransitionEnd: (function (swiper) {
                      var visibleSlides = swiper.visibleSlides;
                      var lastVisibleSlide = Belt_Array.get(visibleSlides, visibleSlides.length - 1 | 0);
                      Belt_Option.forEach(lastVisibleSlide, (function (slide) {
                              var contentEl = slide.firstChild;
                              contentEl.focus();
                            }));
                    }),
                  watchSlidesProgress: true
                }), React.createElement("button", {
                  "aria-controls": "swiper-example",
                  className: "inline-flex items-center rounded border border-transparent bg-indigo-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2",
                  onClick: (function (param) {
                      Belt_Option.forEach(Swiper8.getFromDom(swiperRef.current), (function (prim) {
                              prim.slideNext();
                            }));
                    })
                }, "Next"));
}

export {
  posts ,
  $$default ,
  $$default as default,
}
/*  Not a pure module */
