// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "@rescript/std/lib/es6/curry.js";
import * as React from "react";
import * as ReactSpread from "@seamonster-studios/react-spread/src/ReactSpread.js";
import * as ReachCheckbox from "../src/ReachCheckbox.js";
import * as Checkbox from "@reach/checkbox";

function $$default(param) {
  var match = React.useState(function () {
        return "\\false";
      });
  var setChecked = match[1];
  var inputRef = React.useRef(null);
  var match$1 = Checkbox.useMixedCheckbox(inputRef, {
        checked: match[0],
        onChange: (function (param) {
            return ReachCheckbox.handleOnChange(setChecked, param);
          }),
        disabled: false
      });
  return React.createElement("div", {
              className: "p-4"
            }, React.createElement("label", undefined, React.createElement(ReactSpread.make, {
                      props: match$1[0],
                      children: null
                    }, React.createElement("input", {
                          ref: inputRef
                        }), "This is a checkbox created with Reach Checkbox hook")), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setChecked, (function (param) {
                                    return "mixed";
                                  }));
                    })
                }, "Mix it up"), React.createElement("hr", undefined), "Current state is:", React.createElement("pre", undefined, match$1[1].checked));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
