// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "@rescript/std/lib/es6/curry.js";
import * as React from "react";
import * as ReactSpread from "@seamonster-studios/react-spread/src/ReactSpread.js";
import * as ReachCheckbox from "../src/ReachCheckbox.js";
import * as Checkbox from "@reach/checkbox";

var id = "my-checkbox";

function _ReachCheckboxSingle$CheckField(Props) {
  var checked = Props.checked;
  var handleChange = Props.handleChange;
  var optionLabel = Props.optionLabel;
  var label = Props.label;
  var inputRef = React.useRef(null);
  var match = Checkbox.useMixedCheckbox(inputRef, {
        checked: undefined,
        defaultChecked: checked,
        onChange: (function (param) {
            return Curry._1(handleChange, ReachCheckbox.toggleChecked(checked));
          }),
        disabled: false
      });
  var inputProps = match[0];
  return React.createElement("div", {
              className: "p-4"
            }, React.createElement("label", {
                  className: "block",
                  htmlFor: id
                }, label), React.createElement("div", {
                  className: "flex my-4 items-center justify-start text-left"
                }, React.createElement("div", {
                      className: "flex items-center "
                    }, React.createElement("button", {
                          className: "flex w-4 h-4 border-2 border-black transition-colors duration-300 rounded-sm " + (
                            checked === "true" ? "bg-black" : "bg-transparent"
                          ),
                          type: "button",
                          onClick: inputProps.onChange
                        }), React.createElement(ReactSpread.make, {
                          props: inputProps,
                          children: React.createElement("input", {
                                ref: inputRef,
                                className: "invisible w-0 h-0"
                              })
                        })), React.createElement("button", {
                      className: "flex ml-2",
                      type: "button",
                      onClick: inputProps.onChange
                    }, optionLabel)), "Current state is: ", checked);
}

var CheckField = {
  make: _ReachCheckboxSingle$CheckField
};

function $$default(param) {
  var match = React.useState(function () {
        return "false";
      });
  var setChecked = match[1];
  return React.createElement(_ReachCheckboxSingle$CheckField, {
              checked: match[0],
              handleChange: (function (checked) {
                  return Curry._1(setChecked, (function (param) {
                                return checked;
                              }));
                }),
              optionLabel: "Mix it up",
              label: "This is a checkbox created with Reach Checkbox hook"
            });
}

export {
  id ,
  CheckField ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
