// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "@rescript/std/lib/es6/curry.js";
import * as React from "react";

function use(callback, delay) {
  var savedCallback = React.useRef(function (param) {
        
      });
  React.useEffect((function () {
          savedCallback.current = callback;
          return (function (param) {
                    
                  });
        }), [callback]);
  React.useEffect((function () {
          var tick = function (param) {
            return Curry._1(savedCallback.current, undefined);
          };
          if (delay === undefined) {
            return (function (param) {
                      
                    });
          }
          var id = setInterval(tick, delay);
          return (function (param) {
                    clearInterval(id);
                    
                  });
        }), [delay]);
  
}

export {
  use ,
  
}
/* react Not a pure module */
