// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MomentTimezone from "moment-timezone";

function ofTimezone(date, timezone) {
  return MomentTimezone.tz(date, timezone);
}

export {
  ofTimezone ,
}
/* moment-timezone Not a pure module */
