// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "@rescript/std/lib/es6/belt_Option.js";
import * as Caml_option from "@rescript/std/lib/es6/caml_option.js";

function use(callback, delay) {
  var timeoutRef = React.useRef(undefined);
  var savedCallback = React.useRef(callback);
  React.useEffect((function () {
          savedCallback.current = callback;
          
        }), [callback]);
  React.useEffect((function () {
          timeoutRef.current = Caml_option.some(setTimeout(savedCallback.current, delay));
          return (function (param) {
                    return Belt_Option.forEach(timeoutRef.current, (function (prim) {
                                  clearTimeout(prim);
                                  
                                }));
                  });
        }), [delay]);
  return timeoutRef;
}

export {
  use ,
  
}
/* react Not a pure module */
