// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Faker from "faker";

var Address = {};

var Animal = {};

var Commerce = {};

var Company = {};

var Database = {};

var Datatype = {};

var $$Date = {};

var Finance = {};

var Git = {};

var Hacker = {};

var Helpers = {};

var $$Image = {};

var Internet = {};

var Lorem = {};

var Merseene = {};

var Music = {};

function fullName(param) {
  return Faker.name.firstName() + " " + Faker.name.lastName();
}

var Name = {
  fullName: fullName
};

var Phone = {};

var System = {};

var Time = {};

var Vehicle = {};

export {
  Address ,
  Animal ,
  Commerce ,
  Company ,
  Database ,
  Datatype ,
  $$Date ,
  Finance ,
  Git ,
  Hacker ,
  Helpers ,
  $$Image ,
  Internet ,
  Lorem ,
  Merseene ,
  Music ,
  Name ,
  Phone ,
  System ,
  Time ,
  Vehicle ,
  
}
/* faker Not a pure module */
