// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/std/lib/es6/belt_Option.js";

var StateChangeTypes = {};

function Make(Config) {
  var changesToState = function (changes, state) {
    return {
            isOpen: Belt_Option.getWithDefault(changes.isOpen, state.isOpen),
            selectedItem: changes.selectedItem,
            highlightedIndex: Belt_Option.getWithDefault(changes.highlightedIndex, state.highlightedIndex),
            inputValue: changes.inputValue,
            keysSoFar: state.keysSoFar
          };
  };
  return {
          changesToState: changesToState
        };
}

export {
  StateChangeTypes ,
  Make ,
  
}
/* No side effect */
