// Generated by ReScript, PLEASE EDIT WITH CARE


function Make(Config) {
  var StateChangeTypes = {};
  return {
          StateChangeTypes: StateChangeTypes
        };
}

export {
  Make ,
  
}
/* No side effect */
