// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Downshift$Spread(Props) {
  return React.cloneElement(Props.children, Props.props);
}

var Spread = {
  make: Downshift$Spread
};

var Select;

export {
  Select ,
  Spread ,
  
}
/* react Not a pure module */
