// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function use(value) {
  var reference = React.useRef(value);
  React.useEffect((function () {
          reference.current = value;
          return (function (param) {
                    
                  });
        }), [value]);
  return reference.current;
}

export {
  use ,
}
/* react Not a pure module */
