// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "@rescript/std/lib/es6/curry.js";
import * as React from "react";

function usePrevious(value) {
  var reference = React.useRef(value);
  React.useEffect((function () {
          reference.current = value;
          return (function (param) {
                    
                  });
        }), [value]);
  return reference.current;
}

function UsePrevious$Counter(Props) {
  var children = Props.children;
  var intervalOpt = Props.interval;
  var stepOpt = Props.step;
  var interval = intervalOpt !== undefined ? intervalOpt : 1000;
  var step = stepOpt !== undefined ? stepOpt : 1;
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  React.useEffect((function () {
          setInterval((function (param) {
                  return Curry._1(setCount, (function (c) {
                                return c + step | 0;
                              }));
                }), interval);
          
        }), [
        interval,
        step
      ]);
  return React.createElement("div", {
              className: "p-0"
            }, React.createElement("div", undefined, String(match[0])), children);
}

var Counter = {
  make: UsePrevious$Counter
};

export {
  usePrevious ,
  Counter ,
  
}
/* react Not a pure module */
