// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/std/lib/es6/belt_Option.js";
import * as Caml_option from "@rescript/std/lib/es6/caml_option.js";

var Pagination = {};

var WithProps = {};

var Slide = {
  WithProps: WithProps
};

function getFromDom(el) {
  return Belt_Option.flatMap((el == null) ? undefined : Caml_option.some(el), (function (prim) {
                return Caml_option.nullable_to_opt(prim.swiper);
              }));
}

export {
  Pagination ,
  Slide ,
  getFromDom ,
  
}
/* No side effect */
