// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Swiper8_externalJs from "./Swiper8_external.js";

var Slide = {};

function fixA11y(prim) {
  Swiper8_externalJs.fixA11y(prim);
  
}

export {
  Slide ,
  fixA11y ,
  
}
/* ./Swiper8_external.js Not a pure module */
