// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "@rescript/std/lib/es6/curry.js";
import * as React from "react";
import * as ReactRadioGroup from "@radix-ui/react-radio-group";

function $$default(param) {
  var match = React.useState(function () {
        return "default";
      });
  var setValue = match[1];
  var value = match[0];
  return React.createElement(React.Fragment, undefined, React.createElement("form", undefined, React.createElement(ReactRadioGroup.Root, {
                      value: value,
                      onValueChange: (function (value) {
                          Curry._1(setValue, (function (param) {
                                  return value;
                                }));
                        }),
                      children: null,
                      id: "radix-radio-group",
                      "aria-label": "View density"
                    }, React.createElement("div", {
                          className: "radio-group-item-container"
                        }, React.createElement(ReactRadioGroup.Item, {
                              value: "default",
                              id: "r1",
                              className: "radio-group-item",
                              children: React.createElement(ReactRadioGroup.Indicator, {
                                    className: "radio-group-indicator"
                                  })
                            }), React.createElement("label", {
                              htmlFor: "r1"
                            }, "Default")), React.createElement("div", {
                          className: "radio-group-item-container"
                        }, React.createElement(ReactRadioGroup.Item, {
                              value: "comfortable",
                              id: "r2",
                              className: "radio-group-item",
                              children: React.createElement(ReactRadioGroup.Indicator, {
                                    className: "radio-group-indicator"
                                  })
                            }), React.createElement("label", {
                              htmlFor: "r2"
                            }, "Comfortable")), React.createElement("div", {
                          className: "radio-group-item-container"
                        }, React.createElement(ReactRadioGroup.Item, {
                              value: "compact",
                              id: "r3",
                              className: "radio-group-item",
                              children: React.createElement(ReactRadioGroup.Indicator, {
                                    className: "radio-group-indicator"
                                  })
                            }), React.createElement("label", {
                              htmlFor: "r3"
                            }, "Compact")))), "" + value + " selected");
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
