// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "@rescript/std/lib/es6/curry.js";
import * as React from "react";
import * as Js_option from "@rescript/std/lib/es6/js_option.js";
import * as ReactAccordion from "@radix-ui/react-accordion";

function $$default(param) {
  var match = React.useState(function () {
        
      });
  var setValue = match[1];
  var tmp = {
    type: "single",
    collapsible: true,
    children: null,
    className: "Fixture__RadixAccordion__Root"
  };
  var tmp$1 = match[0];
  if (tmp$1 !== undefined) {
    tmp.value = tmp$1;
  }
  return React.createElement("div", {
              className: "Fixture__RadixAccordion"
            }, React.createElement(ReactAccordion.Root, tmp, React.createElement(ReactAccordion.Item, {
                      value: "item-1",
                      children: null,
                      className: "Fixture__RadixAccordion__Item"
                    }, React.createElement(ReactAccordion.Trigger, {
                          children: "Open Item 1",
                          className: "Fixture__RadixAccordion__Trigger"
                        }), React.createElement(ReactAccordion.Content, {
                          children: React.createElement("div", undefined, "Item 1"),
                          className: "Fixture__RadixAccordion__Content"
                        })), React.createElement(ReactAccordion.Item, {
                      value: "item-2",
                      children: null,
                      className: "Fixture__RadixAccordion__Item"
                    }, React.createElement(ReactAccordion.Trigger, {
                          children: "Open Item 2",
                          className: "Fixture__RadixAccordion__Trigger"
                        }), React.createElement(ReactAccordion.Content, {
                          children: React.createElement("div", undefined, "Item 2"),
                          className: "Fixture__RadixAccordion__Content"
                        }))), React.createElement("div", {
                  className: "mt-10"
                }, React.createElement("button", {
                      className: "bg-gray-200 px-4 py-2 rounded-md border border-gray-300",
                      type: "button",
                      onClick: (function (param) {
                          return Curry._1(setValue, (function (prevValue) {
                                        if (Js_option.isNone(prevValue)) {
                                          return "item-1";
                                        }
                                        
                                      }));
                        })
                    }, "Toggle Item 1")));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
